# -*- coding: utf-8 -*-
"""ADS-B_V2.ipynb

Automatically generated by Colab.

"""

# ===================================================================================
# APPLICATION ARCHITECTURE & DATA FLOW
# ===================================================================================
#
#  +-------------------------------------------------------------------------------+
#  |                                GOOGLE COLAB                                   |
#  |                                                                               |
#  |  +-------------------------------------------------------------------------+  |
#  |  |                   FRONTEND (IFrame / Leaflet.js UI)                     |  |
#  |  |                                                                         |  |
#  |  |  [ User Interaction ]                                                   |  |
#  |  |   ├── Map Click ──> Updates Target Coordinates (Lat, Lon)               |  |
#  |  |   └── Redraws 150 km Red Range Circle on new target coordinates         |  |
#  |  |                                                                         |  |
#  |  |  [ Map Rendering Engine ]                                               |  |
#  |  |   ├── Renders OpenStreetMap tiles                                       |  |
#  |  |   ├── Updates directional SVG aircraft markers                          |  |
#  |  |   └── Generates In-Map Popup Card (Callsign, Altitude, Speed, etc.)     |  |
#  |  +──────────────────────────────────┬────────────────────────────────------+  |
#  |                                     │                                         |
#  |                      HTTP GET /data?lat=...&lon=...                           |
#  |                      (Polling every 3 seconds)                                |
#  |                                     │                                         |
#  |  +----------------------------------▼--------------------------------------+  |
#  |  |                    BACKEND (Python Thread)                              |  |
#  |  |                                                                         |  |
#  |  |  [ 1. Embedded HTTP Server ]                                            |  |
#  |  |   ├── GET /          ──> Serves UI (HTML/JS/Leaflet)                    |  |
#  |  |   └── GET /data?args ──> Triggers targeted data fetch                   |  |
#  |  |                                                                         |  |
#  |  |  [ 2. Data Fetcher & Processor ]                                        |  |
#  |  |   ├── Queries ADS-B APIs for target (Lat, Lon) within ~80 NM radius     |  |
#  |  |   ├── Computes exact Haversine distance from clicked origin             |  |
#  |  |   ├── Filters out aircraft exceeding the strict 150 km radius           |  |
#  |  |   ├── Maps ICAO callsign prefix ──> Airline Name                        |  |
#  |  |   └── Converts units (Feet -> Meters, Knots -> Km/h)                    |  |
#  |  +-------------------------------------------------------------------------+  |
#  +-------------------------------------------------------------------------------+
#
# ===================================================================================


import http.server
import json
import math
import socket
import socketserver
import sys
import threading
import time
import urllib.parse
import urllib.request
from google.colab import output

# ===================================================================================
# DEFAULT CENTER (BARI, ITALY) & RADIUS (150 KM)
# ===================================================================================
DEFAULT_LAT = 41.1171
DEFAULT_LON = 16.8719
RADIUS_KM = 150.0
RADIUS_NM = int(RADIUS_KM * 0.539957) # ~80 Nautical Miles

KNOWN_AIRLINES = {
    "AZA": "ITA Airways", "ITY": "ITA Airways", "RYR": "Ryanair", "WZZ": "Wizz Air",
    "EJU": "easyJet Europe", "EZY": "easyJet", "EZS": "easyJet Switzerland",
    "DHX": "DHL International", "UAE": "Emirates", "ETH": "Ethiopian Airlines",
    "DLH": "Lufthansa", "UPS": "UPS Airlines", "FDX": "FedEx Express",
    "AEE": "Aegean Airlines", "THY": "Turkish Airlines", "VLG": "Vueling",
    "AAL": "American Airlines", "DAL": "Delta Air Lines", "UAL": "United Airlines",
    "BAW": "British Airways", "AFR": "Air France", "KLM": "KLM Royal Dutch Airlines",
    "RAM": "Royal Air Maroc", "SWR": "Swiss International Air Lines",
    "AUA": "Austrian Airlines", "TAP": "TAP Air Portugal", "IAM": "Italian Air Force",
    "NOA": "Neos", "VOE": "Volotea", "AHO": "Air Hamburg", "EWG": "Eurowings"
}

def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2 +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) *
         math.sin(dlon / 2) ** 2)
    return R * (2 * math.atan2(math.sqrt(a), math.sqrt(1 - a)))

def feet_to_meters(feet):
    try:
        return round(float(feet) * 0.3048) if feet not in (None, "ground") else 0
    except (ValueError, TypeError):
        return "N/A"

def knots_to_kmh(knots):
    try:
        return round(float(knots) * 1.852) if knots is not None else "N/A"
    except (ValueError, TypeError):
        return "N/A"

def get_airline_from_callsign(callsign):
    if not callsign or callsign == "N/A":
        return "General / Private"
    prefix = callsign.strip().upper()[:3]
    return KNOWN_AIRLINES.get(prefix, "General / Private")

def query_adsb_api(lat, lon):
    """Executes fast requests to ADS-B APIs for target dynamic coordinates."""
    primary_url = f"https://opendata.adsb.fi/api/v3/lat/{lat}/lon/{lon}/dist/{RADIUS_NM}"
    fallback_url = f"https://api.adsb.lol/v2/lat/{lat}/lon/{lon}/dist/{RADIUS_NM}"

    headers = {"User-Agent": "Mozilla/5.0"}

    try:
        req = urllib.request.Request(primary_url, headers=headers)
        with urllib.request.urlopen(req, timeout=2.5) as resp:
            if resp.status == 200:
                return json.loads(resp.read().decode("utf-8"))
    except Exception:
        pass

    try:
        req = urllib.request.Request(fallback_url, headers=headers)
        with urllib.request.urlopen(req, timeout=2.5) as resp:
            if resp.status == 200:
                return json.loads(resp.read().decode("utf-8"))
    except Exception:
        pass

    return None

def fetch_radar_data(center_lat, center_lon):
    """Fetches aircraft data within 150 km of specified coordinates."""
    raw = query_adsb_api(center_lat, center_lon)
    aircraft_list = []

    if raw and "ac" in raw:
        for ac in raw.get("ac", []):
            lat, lon = ac.get("lat"), ac.get("lon")
            if lat is None or lon is None:
                continue

            dist_km = haversine(center_lat, center_lon, lat, lon)
            if dist_km > RADIUS_KM:
                continue

            hex_id = str(ac.get("hex", "")).upper().strip()
            raw_callsign = ac.get("flight", "")
            callsign = raw_callsign.strip() if raw_callsign else "N/A"
            target_id = hex_id if hex_id != "" else callsign

            if not target_id or target_id == "N/A":
                continue

            aircraft_list.append({
                "id": target_id,
                "hex": hex_id,
                "callsign": callsign,
                "airline": get_airline_from_callsign(callsign),
                "lat": lat,
                "lon": lon,
                "distance_km": round(dist_km, 1),
                "altitude_m": feet_to_meters(ac.get("alt_baro")),
                "speed_kmh": knots_to_kmh(ac.get("gs")),
                "track": round(float(ac.get("track", 0) or 0), 1),
                "aircraft_type": ac.get("t", "N/A"),
                "registration": ac.get("r", "N/A")
            })

    return {
        "timestamp": time.strftime("%H:%M:%S"),
        "center": {"lat": center_lat, "lon": center_lon},
        "count": len(aircraft_list),
        "aircraft": aircraft_list
    }

# ===================================================================================
# FRONTEND INTERFACE (ENGLISH & NO RESET BUTTON)
# ===================================================================================
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dynamic Radar - 150km Radius</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <style>
        html, body {{ height: 100%; margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; }}
        #map {{ height: 100vh; width: 100vw; background: #12161f; cursor: crosshair; }}

        .info-panel {{
            position: absolute;
            top: 15px;
            right: 15px;
            z-index: 1000;
            background: rgba(18, 22, 30, 0.92);
            color: #ffffff;
            padding: 14px 18px;
            border-radius: 8px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.6);
            backdrop-filter: blur(6px);
            border: 1px solid rgba(255, 51, 85, 0.5);
            min-width: 200px;
        }}
        .info-panel h2 {{ margin: 0; font-size: 15px; color: #ff3355; text-transform: uppercase; letter-spacing: 1px; }}
        .info-panel h3 {{ margin: 4px 0 8px 0; font-size: 11px; color: #8a99ad; font-weight: 400; }}
        .info-panel .stats {{ font-size: 13px; color: #00ff88; font-weight: 600; }}

        .plane-icon {{ transition: transform 0.3s linear; }}

        .leaflet-popup-content-wrapper {{
            background: #181c24;
            color: #e2e8f0;
            border-radius: 10px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.7);
            border: 1px solid rgba(255,51,85,0.4);
            font-size: 12px;
            padding: 2px;
        }}
        .leaflet-popup-tip {{ background: #181c24; }}
        .popup-card {{ width: 220px; }}
        .popup-header {{
            background: #222834;
            padding: 8px;
            border-radius: 8px 8px 0 0;
            text-align: center;
            border-bottom: 2px solid #ff3355;
        }}
        .popup-header .callsign {{ font-size: 16px; font-weight: bold; color: #ffffff; }}
        .popup-header .airline {{ font-size: 11px; color: #00d2ff; font-weight: 700; text-transform: uppercase; }}

        .popup-table {{ width: 100%; border-collapse: collapse; margin-top: 4px; }}
        .popup-table td {{ padding: 3px 6px; border-bottom: 1px solid rgba(255,255,255,0.05); }}
        .popup-table td.label {{ color: #718096; font-weight: 600; width: 45%; }}
        .popup-table td.val {{ color: #edf2f7; font-weight: 500; }}
    </style>
</head>
<body>

    <div id="map"></div>

    <div class="info-panel">
        <h2>150 km Radar</h2>
        <h3 id="radar-coords">Click anywhere to scan</h3>
        <div class="stats" id="radar-stats">Loading...</div>
    </div>

    <script>
        const DEFAULT_LAT = {default_lat};
        const DEFAULT_LON = {default_lon};
        const RADIUS_METERS = 150000; // 150 km

        let currentLat = DEFAULT_LAT;
        let currentLon = DEFAULT_LON;

        const map = L.map('map', {{
            zoomControl: true,
            scrollWheelZoom: true
        }}).setView([DEFAULT_LAT, DEFAULT_LON], 7);

        L.tileLayer('https://{{s}}.tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png', {{
            attribution: '&copy; OpenStreetMap',
            maxZoom: 18
        }}).addTo(map);

        // Dynamic Radar Center Marker
        const centerMarker = L.circleMarker([currentLat, currentLon], {{
            radius: 7, fillColor: '#ff0033', color: '#ffffff', weight: 2, fillOpacity: 1
        }}).addTo(map);

        // 150 km Range Circle
        const rangeCircle = L.circle([currentLat, currentLon], {{
            radius: RADIUS_METERS,
            color: '#ff0033',
            weight: 2,
            dashArray: '6, 6',
            fillColor: '#ff0033',
            fillOpacity: 0.05
        }}).addTo(map);

        const planeMarkers = {{}};

        function createPlaneSVG(track) {{
            return `
                <div style="transform: rotate(${{track || 0}}deg); width:30px; height:30px;" class="plane-icon">
                    <svg viewBox="0 0 24 24" width="30" height="30" fill="#00d2ff" stroke="#001122" stroke-width="0.8">
                        <path d="M21 16v-2l-8-5V3.5c0-.83-.67-1.5-1.5-1.5S10 2.67 10 3.5V9l-8 5v2l8-2.5V19l-2 1.5V22l3.5-1 3.5 1v-1.5L14 19v-5.5l8 2.5z"/>
                    </svg>
                </div>
            `;
        }}

        function buildPopupHTML(ac) {{
            return `
                <div class="popup-card">
                    <div class="popup-header">
                        <div class="callsign">${{ac.callsign}}</div>
                        <div class="airline">${{ac.airline}}</div>
                    </div>
                    <table class="popup-table">
                        <tr><td class="label">Altitude:</td><td class="val">${{ac.altitude_m !== "N/A" ? ac.altitude_m + " m" : "N/A"}}</td></tr>
                        <tr><td class="label">Speed:</td><td class="val">${{ac.speed_kmh !== "N/A" ? ac.speed_kmh + " km/h" : "N/A"}}</td></tr>
                        <tr><td class="label">Heading:</td><td class="val">${{ac.track}}°</td></tr>
                        <tr><td class="label">Distance:</td><td class="val">${{ac.distance_km}} km</td></tr>
                        <tr><td class="label">Type:</td><td class="val">${{ac.aircraft_type}}</td></tr>
                    </table>
                </div>
            `;
        }}

        // CLICK MAP EVENT: RE-CENTER RADAR AND FETCH DATA
        map.on('click', function(e) {{
            currentLat = parseFloat(e.latlng.lat.toFixed(4));
            currentLon = parseFloat(e.latlng.lng.toFixed(4));

            centerMarker.setLatLng([currentLat, currentLon]);
            rangeCircle.setLatLng([currentLat, currentLon]);

            updateRadar();
        }});

        async function updateRadar() {{
            document.getElementById('radar-coords').innerText = `Lat: ${{currentLat}}, Lon: ${{currentLon}}`;

            try {{
                const response = await fetch(`/data?lat=${{currentLat}}&lon=${{currentLon}}`);
                if (!response.ok) return;

                const data = await response.json();
                document.getElementById('radar-stats').innerText = `${{data.count}} aircraft in range`;

                const currentIds = new Set();

                data.aircraft.forEach(ac => {{
                    currentIds.add(ac.id);

                    const icon = L.divIcon({{
                        html: createPlaneSVG(ac.track),
                        className: '',
                        iconSize: [30, 30],
                        iconAnchor: [15, 15],
                        popupAnchor: [0, -12]
                    }});

                    if (planeMarkers[ac.id]) {{
                        const marker = planeMarkers[ac.id];
                        marker.setLatLng([ac.lat, ac.lon]);
                        marker.setIcon(icon);
                        const popup = marker.getPopup();
                        if (popup && popup.isOpen()) {{
                            popup.setContent(buildPopupHTML(ac));
                        }}
                    }} else {{
                        const marker = L.marker([ac.lat, ac.lon], {{ icon: icon }}).addTo(map);
                        marker.bindPopup(buildPopupHTML(ac));
                        planeMarkers[ac.id] = marker;
                    }}
                }});

                // Remove markers outside current search radius
                Object.keys(planeMarkers).forEach(id => {{
                    if (!currentIds.has(id)) {{
                        map.removeLayer(planeMarkers[id]);
                        delete planeMarkers[id];
                    }}
                }});

            }} catch (err) {{
                console.warn("Update Error:", err);
            }}
        }}

        updateRadar();
        setInterval(updateRadar, 3000);
    </script>
</body>
</html>
"""

HTML_PAGE = HTML_TEMPLATE.format(
    default_lat=DEFAULT_LAT,
    default_lon=DEFAULT_LON
)

# ==========================================
# HTTP SERVER
# ==========================================
class RadarRequestHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        parsed_url = urllib.parse.urlparse(self.path)

        if parsed_url.path == '/' or parsed_url.path.startswith('/?'):
            self.send_response(200)
            self.send_header('Content-Type', 'text/html; charset=utf-8')
            self.end_headers()
            self.wfile.write(HTML_PAGE.encode('utf-8'))

        elif parsed_url.path == '/data':
            query_params = urllib.parse.parse_qs(parsed_url.query)
            lat = float(query_params.get('lat', [DEFAULT_LAT])[0])
            lon = float(query_params.get('lon', [DEFAULT_LON])[0])

            radar_json = fetch_radar_data(lat, lon)

            self.send_response(200)
            self.send_header('Content-Type', 'application/json; charset=utf-8')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(json.dumps(radar_json).encode('utf-8'))
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, format, *args):
        return

def run_application():
    if hasattr(sys, '_colab_radar_server'):
        try:
            sys._colab_radar_server.shutdown()
            sys._colab_radar_server.server_close()
        except Exception:
            pass

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(('', 0))
        port = s.getsockname()[1]

    class ReusableTCPServer(socketserver.TCPServer):
        allow_reuse_address = True

    server = ReusableTCPServer(("", port), RadarRequestHandler)
    sys._colab_radar_server = server

    threading.Thread(target=server.serve_forever, daemon=True).start()
    print(f"Interactive Radar server running on port {port}.")
    output.serve_kernel_port_as_iframe(port, height=760)

run_application()